FROM node:14.15.1-slim

ARG SOUND_FILES
ARG WORDS_FILE
ARG HISTORY_FOLDER
ARG COMMITHASH
ARG ANALYTICS_ID

WORKDIR /usr/src/app

COPY package*.json ./
RUN npm ci

COPY . .

ENV PORT=3000
ENV SOUND_FILES=$SOUND_FILES
ENV WORDS_FILE=$WORDS_FILE
ENV HISTORY_FOLDER=$HISTORY_FOLDER
ENV COMMITHASH=$COMMITHASH
ENV ANALYTICS_ID=$ANALYTICS_ID

RUN npm run build
RUN npm prune --production

EXPOSE 3000

CMD [ "npm", "start" ]
